server:
#配置启动端口
   port: 80
   max-http-header-size: 4048576
   max-http-post-size: 4048576
   tomcat:
      max-http-post-size: 4048576
spring:
   application:
      name: auto_creater
   datasource:
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite:classpath:/db/connection.db
      username: root
      password: 123456
   freemarker:
      allow-request-override: false
      allow-session-override: false
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      enabled: true
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: true
      prefer-file-system-access: true
      settings:
         classic_compatible: true
         default_encoding: UTF-8
         template_update_delay: 0
      suffix: .ftl
      template-loader-path: classpath:/html/
mybatis-plus:
   mapper-locations: classpath:mapper/*.xml
   typeAliasesPackage: com.cds.app.creater.dal.model
#数据库大写下划线转换
   configuration:
      map-underscore-to-camel-case: true
#capital-mode: true
      cache-enabled: true


example:
   prefix: example
#项目前缀，一般与数据库同名
   projects:
   -  example-dep: https://github.com/CandleDrums/${example.prefix}-dep.git
   -  example-server: https://github.com/CandleDrums/${example.prefix}-server.git
   -  example-api: https://github.com/CandleDrums/${example.prefix}-api.git
#输出目录
   outputPath: /Users/liming/git_temp
   #过滤无用文件
   ignore:
   # maven ignore
   - target/
   - .war
   - .ear
   - .zip
   - .tar
   - .tar.gz
   # eclipse ignore
   - .settings/
   - .project
   - .classpath
   # idea ignore
   - .idea/
   - .ipr
   - .iml
   - .iws
   # logs #
   - logs
   # temp ignore
   - .log
   - .cache
   - .diff
   - .patch
   - .tmp
   - .java~
   - .properties~
   - .xml~
   # system ignore
   - .DS_Store
   - Thumbs.db
   - Servers
   - .metadata
   # other
   - .sts4-cachee
   #git
   - .git/