server:
#配置启动端口
    port: 80
    max-http-header-size: 4048576
    tomcat:
      max-http-form-post-size: 4048576
spring:
    application:
        name: auto-creater
    datasource:
        driver-class-name: org.sqlite.JDBC
#因为系统不同，如果直接使用“:resource:”可能会无法插入值
#*需修改*
        url: jdbc:sqlite:/Users/liming/git_cds/auto-creater/auto-creater-web/src/main/resources/sqlite3.db
        username: null
        password: null
#freemarker配置
    freemarker:
        allow-request-override: false
        allow-session-override: false
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        enabled: true
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: true
        prefer-file-system-access: true
        settings:
            classic_compatible: true
            default_encoding: UTF-8
            template_update_delay: 0
        suffix: .ftl
        template-loader-path: classpath:/static/

#mapper配置
mapper:
  identity: JDBC
  mappers: com.cds.base.dal.dao.BaseDAO
  not-empty: false
logging:
  config: classpath:logback-spring.xml
#相关参数测默认值，可以根据实际情况自行修改
example:
    prefix: example
#项目前缀，一般与数据库同名
    serverProjects:
    -   example-dep: https://github.com/CandleDrums/${example.prefix}-dep.git
    -   example-server: https://github.com/CandleDrums/${example.prefix}-server.git
    -   example-api: https://github.com/CandleDrums/${example.prefix}-api.git
    appProjects:
    -   example-rest-app: https://github.com/CandleDrums/example-rest-app.git
#输出目录
#*需修改*
    outputPath: /Users/liming/Downloads/gittemp
    #应用端口
    port: 10000
    #作者
    author: 自动创建
    #包名
    packageName: com.cds
    #版权
    copyright: (c) 2019 CandleDrumS.com All Right Reserved.
#过滤无用文件
    ignore:
# maven ignore
    - target/
    - .war
    - .ear
    - .zip
    - .tar
    - .tar.gz
# eclipse ignore
    - .settings/
    - .project
    - .classpath
# idea ignore
    - .idea/
    - .ipr
    - .iml
    - .iws
# logs #
    - logs
# temp ignore
    - .log
    - .cache
    - .diff
    - .patch
    - .tmp
    - .java~
    - .properties~
    - .xml~
# system ignore
    - .DS_Store
    - Thumbs.db
    - Servers
    - .metadata
# other
    - .sts4-cachee
#git
    - .git/